name: 模块提交
description: 提交新模块到仓库
title: "[模块提交]: "
labels: ["module-submission"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您提交模块！请填写以下信息以帮助我们更好地处理您的提交。
        
  - type: input
    id: module-name
    attributes:
      label: 模块名称
      description: 请输入模块的名称
      placeholder: "例如: Zygisk Next"
    validations:
      required: true

  - type: input
    id: module-source
    attributes:
      label: 模块地址
      description: 请提供模块的 GitHub/GitLab 仓库地址或其他来源地址
      placeholder: "例如: https://github.com/Dr-TSNG/ZygiskNext"
    validations:
      required: true

  - type: textarea
    id: module-description
    attributes:
      label: 模块描述
      description: 请简要描述该模块的功能
      placeholder: "请描述模块的主要功能和用途..."
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: 提交确认
      description: 提交前请确认以下内容
      options:
        - label: 我已确认该模块可以正常使用
          required: true
        - label: 我已确认该模块未在仓库中重复提交
          required: true 
