name: Update Repository

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mmrl-util
          
      - name: Create required directories and files
        run: |
          mkdir -p modules
          mkdir -p json
          if [ ! -f json/modules.json ]; then
            echo '{"name":"Misaki-Module Repo","website":"https://misak10.github.io/mmrl-repo/","support":"https://github.com/misak10/mmrl-repo/issues","submission":"https://github.com/misak10/mmrl-repo/issues/new","cover":"https://misak10.github.io/mmrl-repo/assets/cover.webp","description":"一个提供各种实用 Magisk 模块的仓库。(自用)","metadata":{"version":1,"timestamp":1704520800.0},"modules":[]}' > json/modules.json
          fi
          
      - name: Update repository
        run: |
          mmrl-util sync
          mmrl-util index
          mmrl-util sitemap
          
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "chore: update repository" || echo "No changes to commit"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} 